version: '3.5'

services:

  es01:
    image: local/elastic
    build:
      context: ./backend/elastic
    container_name: es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es01-data:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200

    
  es02:
    image: local/elastic
    build:
      context: ./backend/elastic
    container_name: es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es02-data:/usr/share/elasticsearch/data 
    
  es03:
    image: local/elastic
    build:
      context: ./backend/elastic
    container_name: es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es03-data:/usr/share/elasticsearch/data 
    
volumes:

  es01-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data01
      o: bind

  es02-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data02
      o: bind

  es03-data:
    driver: local
    driver_opts: 
      type: none
      device: /volume/elastic/data03
      o: bind