version: '3.5'

services:

  jaeger:
    image: local/jaeger
    container_name: jaeger
    hostname: jaeger
    networks:
      - dev-net
    build:
      context: ./backend/jaeger
    ports:
      - "6831:6831"
      - "16686:16686"
    env_file:
      - ./backend/jaeger/.env

