version: '3.5'

services:

  core-nats:
    image: local/nats
    build:
      context: ./backend/nats
    hostname: nats
    container_name: core-nats
    networks:
      - dev-net
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    env_file:
      - ./backend/nats/.env




  # natsboard:
  #   image: local/natsboard
  #   build:
  #     context: ./natsboard/natsboard
  #   hostname: natsboard
  #   container_name: natsboard
  #   networks:
  #     - dev-net
  #     - monitor-net

  # surveyor:
  #   image: synadia/nats-surveyor:${SURVEYOR_DOCKER_TAG}
  #   container_name: nats-surveyor
  #   restart: always
  #   volumes:
  #     - $NATS_SURVEYOR_CREDS:/etc/surveyor/SYS.creds
  #     - ./observations:/observations
  #     - ./jetstream:/jetstream
  #   entrypoint: /nats-surveyor
  #   command: -c ${NATS_SURVEYOR_SERVER_COUNT} -creds /etc/surveyor/SYS.creds -s "${NATS_SURVEYOR_SERVERS}" -observe /observations
  #   networks:
  #     - monitor-net
  #   labels:
  #     org.label-schema.group: "nats-monitoring"

  # prometheus:
  #   image: prom/prometheus:${PROMETHEUS_DOCKER_TAG}
  #   container_name: prometheus
  #   restart: always
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #     - $PROMETHEUS_STORAGE:/usr/local/share/prometheus
  #   command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/usr/local/share/prometheus
  #   networks:
  #     - monitor-net
  #   labels:
  #     org.label-schema.group: "nats-monitoring"
  #   depends_on:
  #     - surveyor

  # grafana:
  #   image: grafana/grafana:${GRAFANA_DOCKER_TAG}
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   networks:
  #     - monitor-net
  #   labels:
  #     org.label-schema.group: "nats-monitoring"
  #   depends_on:
  #     - prometheus      

