version: '3.5'

services:

 wireshark:
   image: local/wireshark
   container_name: wireshark
   hostname: wireshark
   build:
     context: ./backend/wireshark
   cap_add:
     - NET_ADMIN
   security_opt:
     - seccomp:unconfined
   restart: unless-stopped
   network_mode: host      
  #  ports:
  #    - "3000:3000"
  #    - "3001:3001"
   env_file:
     - ./backend/wireshark/.env
   volumes:
     - ws-config:/config


volumes:

  ws-config:
    driver: local
    driver_opts: 
      type: none
      device: /volume/wireshark/config
      o: bind